name: Sample python project testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run tests
        run: |
          print("Welcome to sample python pipeline using GitHub Actions")
