name: sampleproject1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt
       
      - name: Run tests
        run: python -m unittest discover
